--Consecutive Seat Reserve

SELECT '['||XYZ.SEAT_ID||','||ABC.SEAT_ID||']' AS CONS_SEAT FROM 
    (SELECT * FROM CINEMA WHERE FREE=1) ABC
    INNER JOIN (SELECT * FROM CINEMA WHERE FREE=1) XYZ
    ON ABC.SEAT_ID = XYZ.SEAT_ID+1;

SELECT '['||SEAT_ID||','||LEAD_SEAT||']' AS CONS_SEAT FROM (SELECT CN.*,
    LEAD(SEAT_ID) OVER(ORDER BY SEAT_ID) AS LEAD_SEAT,
    LAG(SEAT_ID) OVER(ORDER BY SEAT_ID) AS LAG_SEAT
    FROM CINEMA CN WHERE FREE=1) WHERE LEAD_SEAT = SEAT_ID + 1;
	
---------------------------------------------------------------	
CREATE TABLE CINEMA (
 SEAT_ID NUMBER,
 FREE NUMBER,
 CONSTRAINT PK_SEAT_ID PRIMARY KEY(SEAT_ID));
 
INSERT INTO CINEMA (SEAT_ID, FREE) VALUES (1, 1);
INSERT INTO CINEMA (SEAT_ID, FREE) VALUES (2, 0);
INSERT INTO CINEMA (SEAT_ID, FREE) VALUES (3, 1);
INSERT INTO CINEMA (SEAT_ID, FREE) VALUES (4, 1);
INSERT INTO CINEMA (SEAT_ID, FREE) VALUES (5, 1);
INSERT INTO CINEMA (SEAT_ID, FREE) VALUES (6, 0);
INSERT INTO CINEMA (SEAT_ID, FREE) VALUES (7, 1);
INSERT INTO CINEMA (SEAT_ID, FREE) VALUES (8, 1);
INSERT INTO CINEMA (SEAT_ID, FREE) VALUES (9, 0);
INSERT INTO CINEMA (SEAT_ID, FREE) VALUES (10, 1);
INSERT INTO CINEMA (SEAT_ID, FREE) VALUES (11, 0);
INSERT INTO CINEMA (SEAT_ID, FREE) VALUES (12, 1);
INSERT INTO CINEMA (SEAT_ID, FREE) VALUES (13, 0);
INSERT INTO CINEMA (SEAT_ID, FREE) VALUES (14, 1);
INSERT INTO CINEMA (SEAT_ID, FREE) VALUES (15, 1);
INSERT INTO CINEMA (SEAT_ID, FREE) VALUES (16, 0);
INSERT INTO CINEMA (SEAT_ID, FREE) VALUES (17, 1);
INSERT INTO CINEMA (SEAT_ID, FREE) VALUES (18, 1);
INSERT INTO CINEMA (SEAT_ID, FREE) VALUES (19, 1);
INSERT INTO CINEMA (SEAT_ID, FREE) VALUES (20, 1);
