SELECT EMP.*,
RANK() OVER(ORDER BY SALARY DESC) AS RNK
FROM HR.EMPLOYEES EMP;

SELECT SALARY, COUNT(*) FROM HR.EMPLOYEES
GROUP BY SALARY HAVING COUNT(*) > 1;

SELECT * FROM HR.EMPLOYEES EMP WHERE ROWID < (SELECT MAX(ROWID) FROM HR.EMPLOYEES EMP1 WHERE EMP.SALARY=EMP1.SALARY)
ORDER BY EMP.SALARY;

SELECT * FROM HR.EMPLOYEES EMP WHERE ROWID > (SELECT MIN(ROWID) FROM HR.EMPLOYEES EMP1 WHERE EMP.SALARY=EMP1.SALARY)
ORDER BY EMP.SALARY;

SELECT * FROM HR.EMPLOYEES WHERE ROWID IN
    (SELECT ROWID FROM (
SELECT ROWID,
    ROW_NUMBER() OVER(PARTITION BY SALARY ORDER BY SALARY) AS RN
    FROM HR.EMPLOYEES) WHERE RN > 1);