--Salary Queries

--Find employees whose salary is greater than manager salary
--find employees whose salary is greater than average manager salary
--Find employees whose salary is greater than department average salary salary
--Find top 2 salary in each deparment
--Find top 2 salary under each manager.
SELECT EMP.SALARY, MGR.SALARY FROM HR.EMPLOYEES EMP INNER JOIN HR.EMPLOYEES MGR ON EMP.MANAGER_ID = MGR.EMPLOYEE_ID
WHERE EMP.SALARY > MGR.SALARY; 

SELECT ROUND(AVG(SALARY),2) FROM HR.EMPLOYEES WHERE EMPLOYEE_ID IN(SELECT MANAGER_ID FROM HR.EMPLOYEES);

SELECT EMP.SALARY, MGR.SALARY FROM HR.EMPLOYEES EMP INNER JOIN HR.EMPLOYEES MGR ON EMP.MANAGER_ID = MGR.EMPLOYEE_ID
WHERE EMP.SALARY > (SELECT ROUND(AVG(SALARY),2) FROM HR.EMPLOYEES WHERE EMPLOYEE_ID IN(SELECT MANAGER_ID FROM HR.EMPLOYEES)); 

SELECT EMP.* FROM HR.EMPLOYEES EMP WHERE SALARY > (SELECT AVG(SALARY) FROM HR.EMPLOYEES);

SELECT * FROM(
SELECT EMP.*, AVG(SALARY) OVER(PARTITION BY DEPARTMENT_ID ORDER BY DEPARTMENT_ID) AS DEPT_AVG
FROM HR.EMPLOYEES EMP) WHERE SALARY > DEPT_AVG;

SELECT * FROM (
SELECT EMP.*, RANK() OVER(PARTITION BY DEPARTMENT_ID ORDER BY SALARY DESC) AS RNK
FROM HR.EMPLOYEES EMP) WHERE RNK<=2;

SELECT * FROM (
SELECT EMP.*, DENSE_RANK() OVER(PARTITION BY MANAGER_ID ORDER BY SALARY DESC) AS DRNK
FROM HR.EMPLOYEES EMP) WHERE DRNK<=2;

SELECT EMP.EMPLOYEE_ID, 
SALARY, 
    SUM(SALARY) OVER() AS TOTAL_SUM,
    SUM(SALARY) OVER(ORDER BY EMPLOYEE_ID) AS RSUM,
    ROUND(SALARY/SUM(SALARY) OVER()*100,2)
FROM HR.EMPLOYEES EMP;