SELECT MAX(SALARY) FROM HR.EMPLOYEES WHERE SALARY !=(SELECT MAX(SALARY) FROM HR.EMPLOYEES);

SELECT * FROM HR.EMPLOYEES EMP WHERE 2 = (SELECT COUNT(DISTINCT SALARY) FROM HR.EMPLOYEES EMP1 WHERE EMP.SALARY <= EMP1.SALARY);

SELECT * FROM(
SELECT EMP.*,
    RANK() OVER(ORDER BY SALARY DESC) AS RNK
    FROM HR.EMPLOYEES EMP)
WHERE RNK = 2;

SELECT * FROM HR.EMPLOYEES EMP WHERE SALARY > (SELECT AVG(SALARY) FROM HR.EMPLOYEES EMP1 WHERE EMP.DEPARTMENT_ID = EMP1.DEPARTMENT_ID);

SELECT * FROM (
SELECT EMP.*,
AVG(SALARY) OVER(PARTITION BY DEPARTMENT_ID) AS ASAL
FROM HR.EMPLOYEES EMP) EMP1
WHERE EMP1.SALARY > EMP1.ASAL;